// Mocks generated by Mockito 5.4.6 from annotations
// in mini_library_management/test/providers/notification_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mini_library_management/models/book_model.dart' as _i5;
import 'package:mini_library_management/models/borrow_model.dart' as _i7;
import 'package:mini_library_management/models/message_model.dart' as _i2;
import 'package:mini_library_management/models/notification_model.dart' as _i8;
import 'package:mini_library_management/models/user_model.dart' as _i9;
import 'package:mini_library_management/services/firestore_service.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChatRoomModel_0 extends _i1.SmartFake implements _i2.ChatRoomModel {
  _FakeChatRoomModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i3.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i5.BookModel>> booksStream() =>
      (super.noSuchMethod(
            Invocation.method(#booksStream, []),
            returnValue: _i4.Stream<List<_i5.BookModel>>.empty(),
          )
          as _i4.Stream<List<_i5.BookModel>>);

  @override
  _i4.Future<_i5.BookModel?> getBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getBook, [bookId]),
            returnValue: _i4.Future<_i5.BookModel?>.value(),
          )
          as _i4.Future<_i5.BookModel?>);

  @override
  _i4.Future<String> addBook(_i5.BookModel? book) =>
      (super.noSuchMethod(
            Invocation.method(#addBook, [book]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(this, Invocation.method(#addBook, [book])),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updateBook(_i5.BookModel? book) =>
      (super.noSuchMethod(
            Invocation.method(#updateBook, [book]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBook, [bookId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i7.BorrowModel>> userBorrowsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#userBorrowsStream, [userId]),
            returnValue: _i4.Stream<List<_i7.BorrowModel>>.empty(),
          )
          as _i4.Stream<List<_i7.BorrowModel>>);

  @override
  _i4.Stream<List<_i7.BorrowModel>> allBorrowsStream() =>
      (super.noSuchMethod(
            Invocation.method(#allBorrowsStream, []),
            returnValue: _i4.Stream<List<_i7.BorrowModel>>.empty(),
          )
          as _i4.Stream<List<_i7.BorrowModel>>);

  @override
  _i4.Future<String> createBorrow(_i7.BorrowModel? borrow) =>
      (super.noSuchMethod(
            Invocation.method(#createBorrow, [borrow]),
            returnValue: _i4.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#createBorrow, [borrow]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updateBorrowStatus({
    required String? borrowId,
    required String? newStatus,
    required String? bookId,
    DateTime? returnDate,
    bool? restoreCopy = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBorrowStatus, [], {
              #borrowId: borrowId,
              #newStatus: newStatus,
              #bookId: bookId,
              #returnDate: returnDate,
              #restoreCopy: restoreCopy,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i8.NotificationModel>> notificationsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#notificationsStream, [userId]),
            returnValue: _i4.Stream<List<_i8.NotificationModel>>.empty(),
          )
          as _i4.Stream<List<_i8.NotificationModel>>);

  @override
  _i4.Future<void> addNotification(_i8.NotificationModel? notification) =>
      (super.noSuchMethod(
            Invocation.method(#addNotification, [notification]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markNotificationAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationAsRead, [notificationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markNotificationsAsReadBatch(
    List<String>? notificationIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationsAsReadBatch, [notificationIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ChatRoomModel> getOrCreateChatRoom(
    String? userId1,
    String? userId2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateChatRoom, [userId1, userId2]),
            returnValue: _i4.Future<_i2.ChatRoomModel>.value(
              _FakeChatRoomModel_0(
                this,
                Invocation.method(#getOrCreateChatRoom, [userId1, userId2]),
              ),
            ),
          )
          as _i4.Future<_i2.ChatRoomModel>);

  @override
  _i4.Stream<List<_i2.ChatRoomModel>> chatRoomsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#chatRoomsStream, [userId]),
            returnValue: _i4.Stream<List<_i2.ChatRoomModel>>.empty(),
          )
          as _i4.Stream<List<_i2.ChatRoomModel>>);

  @override
  _i4.Stream<List<_i2.MessageModel>> messagesStream(String? chatRoomId) =>
      (super.noSuchMethod(
            Invocation.method(#messagesStream, [chatRoomId]),
            returnValue: _i4.Stream<List<_i2.MessageModel>>.empty(),
          )
          as _i4.Stream<List<_i2.MessageModel>>);

  @override
  _i4.Future<void> sendMessage({
    required String? chatRoomId,
    required _i2.MessageModel? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatRoomId: chatRoomId,
              #message: message,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i9.UserModel?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i4.Future<_i9.UserModel?>.value(),
          )
          as _i4.Future<_i9.UserModel?>);

  @override
  _i4.Stream<List<_i9.UserModel>> adminUsersStream() =>
      (super.noSuchMethod(
            Invocation.method(#adminUsersStream, []),
            returnValue: _i4.Stream<List<_i9.UserModel>>.empty(),
          )
          as _i4.Stream<List<_i9.UserModel>>);
}
