// Mocks generated by Mockito 5.4.6 from annotations
// in mini_library_management/test/screens/book_catalog_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i8;
import 'dart:ui' as _i4;

import 'package:mini_library_management/models/book_model.dart' as _i6;
import 'package:mini_library_management/providers/auth_provider.dart' as _i2;
import 'package:mini_library_management/providers/book_provider.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i2.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> register(String? name, String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [name, email, password]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateName(String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [newName]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateAvatar(String? avatarUrl) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvatar, [avatarUrl]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [BookProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookProvider extends _i1.Mock implements _i5.BookProvider {
  MockBookProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i6.BookModel> get books =>
      (super.noSuchMethod(
            Invocation.getter(#books),
            returnValue: <_i6.BookModel>[],
          )
          as List<_i6.BookModel>);

  @override
  List<_i6.BookModel> get allBooks =>
      (super.noSuchMethod(
            Invocation.getter(#allBooks),
            returnValue: <_i6.BookModel>[],
          )
          as List<_i6.BookModel>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.getter(#searchQuery),
            ),
          )
          as String);

  @override
  Map<String, int> get categoryCounts =>
      (super.noSuchMethod(
            Invocation.getter(#categoryCounts),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void startListening() => super.noSuchMethod(
    Invocation.method(#startListening, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void setSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#setSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void setCategory(String? category) => super.noSuchMethod(
    Invocation.method(#setCategory, [category]),
    returnValueForMissingStub: null,
  );

  @override
  void clearFilters() => super.noSuchMethod(
    Invocation.method(#clearFilters, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<bool> addBook({
    required String? title,
    required String? author,
    required String? isbn,
    required String? category,
    required String? description,
    required int? totalCopies,
    _i8.File? coverImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addBook, [], {
              #title: title,
              #author: author,
              #isbn: isbn,
              #category: category,
              #description: description,
              #totalCopies: totalCopies,
              #coverImage: coverImage,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> updateBook({
    required _i6.BookModel? existing,
    required String? title,
    required String? author,
    required String? isbn,
    required String? category,
    required String? description,
    required int? totalCopies,
    _i8.File? coverImage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBook, [], {
              #existing: existing,
              #title: title,
              #author: author,
              #isbn: isbn,
              #category: category,
              #description: description,
              #totalCopies: totalCopies,
              #coverImage: coverImage,
            }),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<bool> deleteBook(_i6.BookModel? book) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBook, [book]),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  void addListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i4.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
