// Mocks generated by Mockito 5.4.6 from annotations
// in mini_library_management/test/screens/chat_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:ui' as _i5;

import 'package:mini_library_management/models/book_model.dart' as _i8;
import 'package:mini_library_management/models/borrow_model.dart' as _i10;
import 'package:mini_library_management/models/message_model.dart' as _i2;
import 'package:mini_library_management/models/notification_model.dart' as _i11;
import 'package:mini_library_management/models/user_model.dart' as _i12;
import 'package:mini_library_management/providers/auth_provider.dart' as _i6;
import 'package:mini_library_management/providers/chat_provider.dart' as _i3;
import 'package:mini_library_management/services/firestore_service.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeChatRoomModel_0 extends _i1.SmartFake implements _i2.ChatRoomModel {
  _FakeChatRoomModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatProvider extends _i1.Mock implements _i3.ChatProvider {
  MockChatProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i2.ChatRoomModel> get chatRooms =>
      (super.noSuchMethod(
            Invocation.getter(#chatRooms),
            returnValue: <_i2.ChatRoomModel>[],
          )
          as List<_i2.ChatRoomModel>);

  @override
  List<_i2.MessageModel> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i2.MessageModel>[],
          )
          as List<_i2.MessageModel>);

  @override
  bool get isLoadingRooms =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingRooms),
            returnValue: false,
          )
          as bool);

  @override
  bool get isLoadingMessages =>
      (super.noSuchMethod(
            Invocation.getter(#isLoadingMessages),
            returnValue: false,
          )
          as bool);

  @override
  bool get isSending =>
      (super.noSuchMethod(Invocation.getter(#isSending), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void listenToChatRooms(String? userId) => super.noSuchMethod(
    Invocation.method(#listenToChatRooms, [userId]),
    returnValueForMissingStub: null,
  );

  @override
  void stopListening() => super.noSuchMethod(
    Invocation.method(#stopListening, []),
    returnValueForMissingStub: null,
  );

  @override
  void openChatRoom(String? chatRoomId) => super.noSuchMethod(
    Invocation.method(#openChatRoom, [chatRoomId]),
    returnValueForMissingStub: null,
  );

  @override
  void closeChatRoom() => super.noSuchMethod(
    Invocation.method(#closeChatRoom, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i2.ChatRoomModel> getOrCreateChatRoom(
    String? currentUserId,
    String? otherUserId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateChatRoom, [
              currentUserId,
              otherUserId,
            ]),
            returnValue: _i4.Future<_i2.ChatRoomModel>.value(
              _FakeChatRoomModel_0(
                this,
                Invocation.method(#getOrCreateChatRoom, [
                  currentUserId,
                  otherUserId,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.ChatRoomModel>);

  @override
  _i4.Future<bool> sendMessage({
    required String? chatRoomId,
    required String? senderId,
    required String? text,
    String? senderName,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatRoomId: chatRoomId,
              #senderId: senderId,
              #text: text,
              #senderName: senderName,
            }),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i6.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> signIn(String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [email, password]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<bool> register(String? name, String? email, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#register, [name, email, password]),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateName(String? newName) =>
      (super.noSuchMethod(
            Invocation.method(#updateName, [newName]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateAvatar(String? avatarUrl) =>
      (super.noSuchMethod(
            Invocation.method(#updateAvatar, [avatarUrl]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearError() => super.noSuchMethod(
    Invocation.method(#clearError, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i5.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FirestoreService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirestoreService extends _i1.Mock implements _i7.FirestoreService {
  MockFirestoreService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i8.BookModel>> booksStream() =>
      (super.noSuchMethod(
            Invocation.method(#booksStream, []),
            returnValue: _i4.Stream<List<_i8.BookModel>>.empty(),
          )
          as _i4.Stream<List<_i8.BookModel>>);

  @override
  _i4.Future<_i8.BookModel?> getBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#getBook, [bookId]),
            returnValue: _i4.Future<_i8.BookModel?>.value(),
          )
          as _i4.Future<_i8.BookModel?>);

  @override
  _i4.Future<String> addBook(_i8.BookModel? book) =>
      (super.noSuchMethod(
            Invocation.method(#addBook, [book]),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(this, Invocation.method(#addBook, [book])),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updateBook(_i8.BookModel? book) =>
      (super.noSuchMethod(
            Invocation.method(#updateBook, [book]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBook(String? bookId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBook, [bookId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i10.BorrowModel>> userBorrowsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#userBorrowsStream, [userId]),
            returnValue: _i4.Stream<List<_i10.BorrowModel>>.empty(),
          )
          as _i4.Stream<List<_i10.BorrowModel>>);

  @override
  _i4.Stream<List<_i10.BorrowModel>> allBorrowsStream() =>
      (super.noSuchMethod(
            Invocation.method(#allBorrowsStream, []),
            returnValue: _i4.Stream<List<_i10.BorrowModel>>.empty(),
          )
          as _i4.Stream<List<_i10.BorrowModel>>);

  @override
  _i4.Future<String> createBorrow(_i10.BorrowModel? borrow) =>
      (super.noSuchMethod(
            Invocation.method(#createBorrow, [borrow]),
            returnValue: _i4.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#createBorrow, [borrow]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> updateBorrowStatus({
    required String? borrowId,
    required String? newStatus,
    required String? bookId,
    DateTime? returnDate,
    bool? restoreCopy = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateBorrowStatus, [], {
              #borrowId: borrowId,
              #newStatus: newStatus,
              #bookId: bookId,
              #returnDate: returnDate,
              #restoreCopy: restoreCopy,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i11.NotificationModel>> notificationsStream(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#notificationsStream, [userId]),
            returnValue: _i4.Stream<List<_i11.NotificationModel>>.empty(),
          )
          as _i4.Stream<List<_i11.NotificationModel>>);

  @override
  _i4.Future<void> addNotification(_i11.NotificationModel? notification) =>
      (super.noSuchMethod(
            Invocation.method(#addNotification, [notification]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markNotificationAsRead(String? notificationId) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationAsRead, [notificationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markNotificationsAsReadBatch(
    List<String>? notificationIds,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#markNotificationsAsReadBatch, [notificationIds]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ChatRoomModel> getOrCreateChatRoom(
    String? userId1,
    String? userId2,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getOrCreateChatRoom, [userId1, userId2]),
            returnValue: _i4.Future<_i2.ChatRoomModel>.value(
              _FakeChatRoomModel_0(
                this,
                Invocation.method(#getOrCreateChatRoom, [userId1, userId2]),
              ),
            ),
          )
          as _i4.Future<_i2.ChatRoomModel>);

  @override
  _i4.Stream<List<_i2.ChatRoomModel>> chatRoomsStream(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#chatRoomsStream, [userId]),
            returnValue: _i4.Stream<List<_i2.ChatRoomModel>>.empty(),
          )
          as _i4.Stream<List<_i2.ChatRoomModel>>);

  @override
  _i4.Stream<List<_i2.MessageModel>> messagesStream(String? chatRoomId) =>
      (super.noSuchMethod(
            Invocation.method(#messagesStream, [chatRoomId]),
            returnValue: _i4.Stream<List<_i2.MessageModel>>.empty(),
          )
          as _i4.Stream<List<_i2.MessageModel>>);

  @override
  _i4.Future<void> sendMessage({
    required String? chatRoomId,
    required _i2.MessageModel? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #chatRoomId: chatRoomId,
              #message: message,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i12.UserModel?> getUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUser, [userId]),
            returnValue: _i4.Future<_i12.UserModel?>.value(),
          )
          as _i4.Future<_i12.UserModel?>);

  @override
  _i4.Stream<List<_i12.UserModel>> adminUsersStream() =>
      (super.noSuchMethod(
            Invocation.method(#adminUsersStream, []),
            returnValue: _i4.Stream<List<_i12.UserModel>>.empty(),
          )
          as _i4.Stream<List<_i12.UserModel>>);
}
